// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'ws_member_info_res.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

WsMemberInfoRes _$WsMemberInfoResFromJson(Map<String, dynamic> json) => WsMemberInfoRes(
      userName: json['userName'] as String?,
      agentName: json['agentName'] as String?,
      hometown: json['hometown'] as String?,
      occupation: json['occupation'] as String?,
      annualIncome: json['annualIncome'] as String?,
      education: json['education'] as String?,
      gender: json['gender'] as num?,
      age: json['age'] as num?,
      maritalStatus: json['maritalStatus'] as num?,
      weight: json['weight'] as num?,
      height: json['height'] as num?,
      selfIntroduction: json['selfIntroduction'] as String?,
      location: json['location'] as String?,
      updateTime: json['updateTime'] as int?,
      album: json['album'] as String?,
      albumsPath: (json['albumsPath'] as List).map((album) => AlbumsPathInfo.fromJson(album)).toList(),
      avatarAuth: json['avatarAuth'] as num?,
      avatar: json['avatar'] as String?,
      avatarPath: json['avatarPath'] as String?,
      audioAuth: json['audioAuth'] as num?,
      audio: json['audio'] as num?,
      audioPath: json['audioPath'] as String?,
      nickNameAuth: json['nickNameAuth'] as num?,
      nickName: json['nickName'] as String?,
      realNameAuth: json['realNameAuth'] as num?,
      charmLevel: json['charmLevel'] as num?,
      charmPoints: json['charmPoints'] as num?,
      isFollow: json['isFollow'] as bool?,
      realPersonAuth: json['realPersonAuth'] as num?,
      tag: json['tag'] as String?,
      charmCharge: json['charmCharge'] as String?,
      tvStatus: json['tvStatus'] as num?,
      isOnline: json['isOnline'] as num?,
      regTime: json['regTime'] as dynamic,
      agentLevel: json['agentLevel'] as num?,
      osType: json['osType'] as num?,
      lockStatus: json['lockStatus'] as num?,
      parent: json['parent'] as num?,
      type: json['type'] as num?,
    );

Map<String, dynamic> _$WsMemberInfoResToJson(WsMemberInfoRes instance) => <String, dynamic>{
      'userName': instance.userName,
      'agentName': instance.agentName,
      'hometown': instance.hometown,
      'occupation': instance.occupation,
      'annualIncome': instance.annualIncome,
      'education': instance.education,
      'gender': instance.gender,
      'age': instance.age,
      'maritalStatus': instance.maritalStatus,
      'weight': instance.weight,
      'height': instance.height,
      'selfIntroduction': instance.selfIntroduction,
      'location': instance.location,
      'updateTime': instance.updateTime,
      'album': instance.album,
      'albumsPath': instance.albumsPath,
      'avatarAuth': instance.avatarAuth,
      'avatar': instance.avatar,
      'avatarPath': instance.avatarPath,
      'audioAuth': instance.audioAuth,
      'audio': instance.audio,
      'audioPath': instance.audioPath,
      'nickNameAuth': instance.nickNameAuth,
      'nickName': instance.nickName,
      'realNameAuth': instance.realNameAuth,
      'charmLevel': instance.charmLevel,
      'isFollow': instance.isFollow,
      'realPersonAuth': instance.realPersonAuth,
      'tag': instance.tag,
      'charmCharge': instance.charmCharge,
      'tvStatus': instance.tvStatus,
      'isOnline': instance.isOnline,
      'regTime': instance.regTime,
      'agentLevel': instance.agentLevel,
      'charmPoints': instance.charmPoints,
      'osType': instance.osType,
      'lockStatus': instance.lockStatus,
      'parent': instance.parent,
      'type': instance.type,
    };

AlbumsPathInfo _$AlbumsPathInfoFromJson(Map<String, dynamic> json) => AlbumsPathInfo(
      id: json['id'] as num?,
      status: json['status'] as num?,
      filePath: json['filePath'] as String?,
      fileType: json['fileType'] as String?,
    );

Map<String, dynamic> _$AlbumsPathInfoToJson(AlbumsPathInfo instance) => <String, dynamic>{
      'id': instance.id,
      'status': instance.status,
      'filePath': instance.filePath,
      'fileType': instance.fileType,
    };
