import 'package:flutter/material.dart';
import 'package:frechat/system/assets_path/assets_images_path.dart';

@immutable
class
AppImages {
  const AppImages._();

  static const String splashBg = 'assets/images/splash_bg.png';
  static const String loginBg = 'assets/images/login_bg.png';
  static const String phoneLoginBg = 'assets/images/phone_login_bg.png';
  static const String iconBack = 'assets/images/back.png';
  static const String iconPhone = 'assets/images/icon_phone.png';
  static const String iconVerificationCode = 'assets/images/icon_verificationcode.png';
  static const String personalTabHome = '';
  static const String profileContactCoinOrangeIcon = 'assets/profile/profile_contact_coin_orange_icon.png';
  static const String profileDepositWalletBtnIcon = 'assets/profile/profile_deposit_wallet_btn_icon.png';
  static const String profileBenefitWalletBtnIcon = 'assets/profile/profile_benefit_wallet_btn_icon.png';
  static const String friendEmptyBanner = 'assets/profile/profile_friend_empty_img.png';
  static const String strikeUp = 'assets/home/tab/strikeup.svg';
  static const String strikeUpLight = 'assets/home/tab/strikeup_light.svg';
  static const String messenger = 'assets/home/tab/messenger.svg';
  static const String messengerUnread = 'assets/home/tab/messenger_unread.svg';
  static const String messengerLight = 'assets/home/tab/messenger_light.svg';
  static const String messengerLightUnread = 'assets/home/tab/messenger_light_unread.svg';
  static const String profile = 'assets/home/tab/profile.svg';
  static const String profileLight = 'assets/home/tab/profile_light.svg';
  static const String imageMessageEmpty = 'assets/images/image_message_empty.png';
  static const String imageCohesionEmpty = 'assets/images/image_cohesion_empty.png';
  static const String imageCallEmpty = 'assets/images/image_message_empty.png';
  static const String imageVisitorEmpty = 'assets/images/image_novisitor.png';
  static const String missionBgIcon = 'assets/task_center_view/icon_bg_img.png';
  static const String missionCoinIcon = 'assets/strike_up_list/ic_coin.png';
  static const String iconRightArrow = 'assets/images/icon_next.png';
  static const String appIcon = 'assets/images/app_icon.png';
  static const String imageContactEmpty = 'assets/images/image_message_empty.png';
  static const String imageDetailEmpty = 'assets/profile/profile_score_empty_friend.png';
  ///josh
  static const String teenSettingDialogImage= 'assets/profile/profile_teen_close_mode_img.png';
  static const String teenSettingOpenImage = 'assets/profile/profile_teen_open_mode_img.png';
  static const String teenSettingCloseImage = 'assets/profile/profile_teen_close_mode_img.png';
  static const String teenSettingInputImage = 'assets/images/banner_teen_mode.png';
  static const String versionUpdateBackgroundImage = 'assets/images/img_version_update_background.png';
  static const String registerAvatarDefault = 'assets/avatar/register_default.png';
  static const String registerAvatarDefaultMale = 'assets/avatar/male_default_avatar.png';
  static const String registerAvatarDefaultFemale = 'assets/avatar/female_default_avatar.png';
  static const String howToTv = 'assets/tv/icon_tv.png';
  static const String howToTvArrow = 'assets/tv/icon_tv_next.png';
  static const String howToTvTitleWantOnTV = 'assets/strike_up_tv/strike_up_tv_headline_icon_1.png';
  static const String howToTvTitleAnonymous = 'assets/strike_up_tv/strike_up_tv_headline_icon_2.png';
  static const String howToTvTitleNumberOne = 'assets/strike_up_tv/strike_up_tv_num_icon_1.png';
  static const String howToTvTitleNumberTwo = 'assets/strike_up_tv/strike_up_tv_num_icon_2.png';

  // Chris
  static const String iconCoin = 'assets/images/icon_coin.png';
  static const String iconStrikeUpUnselect = AssetsImagesPath.iconTabStrikeUpUnselect;
  static const String iconStrikeUpSelected = AssetsImagesPath.iconTabStrikeUpSelected;
  static const String iconActivityUnselect = AssetsImagesPath.iconTabActivityUnselect;
  static const String iconActivitySelected = AssetsImagesPath.iconTabActivitySelected;
  static const String iconVideoUnselect = AssetsImagesPath.iconTabVideoUnselect;
  static const String iconVideoSelected = AssetsImagesPath.iconTabVideoSelected;
  static const String iconMessageUnselect = AssetsImagesPath.iconTabMessageUnselect;
  static const String iconMessageSelected = AssetsImagesPath.iconTabMessageSelected;
  static const String iconProfileUnselect = AssetsImagesPath.iconTabProfileUnselect;
  static const String iconProfileSelected = AssetsImagesPath.iconTabProfileSelected;
  static const String iconAppSmall = 'assets/images/icon_app_small.png';
  static const String iconTagRealPerson = 'assets/images/icon_tag_real_person.png';
  static const String iconTagRealName = 'assets/images/icon_tag_real_name.png';
  static const String pullLoaderRefreshIcon = 'assets/strike_up_list/refresh_don.png';
  static const String pullLoaderFetchMoreIcon = 'assets/strike_up_list/refresh_up.png';
  static const String pullLoaderLoadingIcon = 'assets/strike_up_list/refresh_Icon.png';
  static const String strikeUpListSearchEmpty = 'assets/strike_up_list/frechat/img_search_empty.png';
  static const String javaSystemIcon = 'assets/avatar/system_avatar.png';
  static const String imgHowToTVBanner = 'assets/strike_up_tv/strike_up_tv_img_1.png';
  static const String imgHowToTVTitle = 'assets/strike_up_tv/strike_up_tv_banner_img_1.png';
  static const String imgHowToTVHeadline = 'assets/strike_up_tv/strike_up_tv_banner_img_2.png';
  static const String iconUserInfoViewAudioPlay = 'assets/icons/icon_play.png';
  static const String iconUserInfoViewAudioPause = 'assets/icons/icon_pause.png';
  static const String iconPersonalProfileEdit = 'assets/icons/icon_edit.png';
  static const String iconAddFile = 'assets/profile/icon_add_file.png';
  static const String certificationStatusIcon = 'assets/images/icon_check.png';
  static const String basicInformationIcon = 'assets/images/icon_info.png';
  static const String recentPhotosIcon = 'assets/images/icon_picture.png';
  static const String iconAgreeCheck = 'assets/icons/icon_agree_check.png';
  static const String iconAgreeUncheck = 'assets/icons/icon_agree_uncheck.png';
  static const String missionCompleteImage = 'assets/images/banner_mission.png';
  static const String checkBoxTrueIcon = 'assets/strike_up_list/check_box_true.png';
  static const String checkBoxFalseIcon = 'assets/strike_up_list/check_box_false.png';
  static const String profileBenefitBtnIcon = 'assets/profile/profile_benefit_btn_icon.png';
  static const String iconAudioRecording = 'assets/icons/icon_audio_recording.png';
  static const String iconAudioRecord = 'assets/icons/icon_audio_record.png';
  static const String bottomSheetCancelBtnIcon = 'assets/images/icon_bottom_sheet_cancel.png';
  static const String iconCopy = 'assets/icons/icon_copy.png';
  static const String chatroomIconCollapse = 'assets/images/icon_collapse.png';
  static const String chatroomIconExpand = 'assets/images/icon_expand.png';
  static const String firstRechargeImage = 'assets/images/first_recharge.png';
  static const String iconCancel = 'assets/images/icon_cancel.png';

  static const String iconActivityPostImage = 'assets/activity/icon_activity_post_image.png';
  static const String iconActivityPostVideo = 'assets/activity/icon_activity_post_video.png';
  static const String iconActivityPostHint = 'assets/activity/icon_activity_hint.png';
  static const String iconActivityPostLocation = 'assets/activity/icon_activity_location.png';
  static const String iconActivityPostCancel = 'assets/activity/icon_activity_cancel.png';
  static const String iconActivityVideoPlaySmall = 'assets/activity/icon_video_play_small.png';
  static const String iconActivityVideoPlayLarge = 'assets/activity/icon_video_play_large.png';
  static const String iconActivityVideoPauseSmall = 'assets/activity/icon_video_pause_small.png';
  static const String iconActivityVideoPauseLarge = 'assets/activity/icon_video_pause_large.png';
  static const String iconActivityMore = 'assets/activity/icon_activity_more.png';
  static const String iconActivityPostTypePhoto = 'assets/activity/icon_post_type_photo.png';
  static const String iconActivityPostTypeVideo = 'assets/activity/icon_post_type_video.png';
  static const String iconActivityNotification = 'assets/activity/icon_activity_notification.png';
  static const String iconActivityNotificationUnread = 'assets/activity/icon_activity_notification_unread.png';
  static const String iconActivityPostButton = 'assets/images/icon_activity_post.png';
  static const String chatroomIconSend = 'assets/images/icon_send.png';
  static const String chatroomIconMicNotRecording = AssetsImagesPath.iconMicNotRecording;
  static const String chatroomIconMicReadyToRecord = AssetsImagesPath.iconMicReadyToRecord;
  static const String chatroomIconMicRecording = AssetsImagesPath.iconMicRecording;
  static const String chatroomIconMicRecordingCompleted = AssetsImagesPath.iconMicRecordingCompleted;
  static const String iconActivityPostDonate = 'assets/activity/icon_activity_donate.png';
  static const String iconActivityPostLike = 'assets/images/icon_activity_like.png';
  static const String iconActivityPostAlreadyLike = 'assets/images/icon_activity_already_like.png';
  static const String iconActivityPostMessage = 'assets/images/icon_activity_message.png';
  static const String iconActivityArrowForward = 'assets/activity/icon_activity_arrow_forward.png';
  static const String imageActivityEmpty = 'assets/images/image_cohesion_empty.png';
  static const String intimacyButtonCancel = 'assets/images/button_cancel.png';
  static const String iconPersonalCertificationPhone = 'assets/icons/icon_certification_phone.png';
  static const String iconPersonalCertificationPersonal = 'assets/icons/icon_certification_personal.png';
  static const String iconPersonalCertificationName = 'assets/icons/icon_certification_name.png';
  static const String iconPersonalCertificationHint = 'assets/icons/icon_certification_hint.png';
  static const String defaultFemaleAvatar = 'assets/avatar/female_default_avatar.png';
  static const String defaultMaleAvatar = 'assets/avatar/male_default_avatar.png';
  static const String iconKBArrowUp = 'assets/icons/icon_kb_arrow_up.png';
  static const String iconKBArrowDown = 'assets/icons/icon_kb_arrow_down.png';
  static const String iconOnlineService = 'assets/icons/icon_online_service.png';
  static const String iconMaleSelected = 'assets/register/icon_male_selected.png';
  static const String iconMaleUnSelect = 'assets/register/icon_male_unselect.png';
  static const String iconFemaleSelected = 'assets/register/icon_female_selected.png';
  static const String iconFemaleUnSelect = 'assets/register/icon_female_unselect.png';
  static const String strikeUpVoiceMateBackgroundImage = 'assets/video_dating/strike_up_mate_background.png';
  static const String strikeUpVideoMateBackgroundImage = 'assets/video_dating/strike_up_mate_background.png';
  static const String strikeUpMateSearchBackgroundImage = 'assets/video_dating/strike_up_mate_search_background.png';
  static const String strikeUpVoiceMateImage = 'assets/video_dating/strike_up_voice_mate.png';
  static const String strikeUpVideoMateImage = 'assets/video_dating/strike_up_video_mate.png';
  static const String disabledPersonalizedSettingImage = 'assets/images/image_cohesion_empty.png';
  static const String iconTagRealNameAuth = 'assets/icons/icon_real_name_auth.png';
  static const String iconTagRealPersonAuth = 'assets/icons/icon_real_person_auth.png';
  static const String iconCallingFree = 'assets/icons/icon_calling_free.png';
  static const String iconOnline = 'assets/icons/icon_online.png';
  static const String iconVip = 'assets/icons/icon_vip.png';
  static const String iconPoints = 'assets/icons/icon_points.png';
  static const String iconExchange = 'assets/icons/icon_exchange.png';
  static const String reportPageTitleIcon = 'assets/images/report_icon.png';
  static const String promotionCenterIconlink = 'assets/images/icon_link.png';
  static const String promotionCenterIconQrcode = 'assets/images/icon_qrcode.png';
  static const String promotionCenterIconWechatFreind = 'assets/images/icon_wechat_friend.png';
  static const String promotionCenterIconWechatMoments = 'assets/images/icon_wechat_moments.png';
  static const String iconChat = 'assets/icons/icon_chat.png';
  static const String iconStrikeUp = 'assets/icons/icon_heart.png';
  static const String iconPinTop = 'assets/images/icon_pin_top.png';
  static const String wechatShareAppIcon = 'assets/images/frechat_app_logo.png';
  static const String imgBlockEmptyBanner = 'assets/profile/profile_setting_empty_block.png';
  static const String iconProfileAgentIncome = 'assets/agent/icon_wallet.png';
  static const String iconProfileAgentText = 'assets/agent/icon_message.png';
  static const String iconProfileAgentGift = 'assets/agent/icon_gift.png';
  static const String iconProfileAgentCallVoice = 'assets/agent/icon_call.png';
  static const String iconProfileAgentCallVideo = 'assets/agent/icon_video.png';
  static const String iconProfileAgentStrikeUp = 'assets/agent/icon_love.png';
  static const String iconProfileAgentActivityDonate = 'assets/agent/icon_donate.png';
  static const String iconProfileAgentCopy = 'assets/profile/icon_profile_agent_copy.png';
  static const String iconProfileAgentWallet = 'assets/profile/icon_profile_agent_wallet.png';
  static const String iconProfileAgentTime = 'assets/profile/icon_profile_agent_clock.png';
  static const String iconProfileAgentHeart = 'assets/profile/icon_profile_agent_heart.png';
  static const String iconProfileAgentMedalStar = 'assets/profile/icon_profile_agent_medal-star.png';
  static const String iconProfileAgentHelp = 'assets/profile/icon_profile_agent_help.png';
  static const String imageProfileContactTodayItem = 'assets/profile/profile_contact_yellow_image.png';
  static const String imageProfileContactWeekItem = 'assets/profile/profile_contact_orange_image.png';
  static const String imageProfileContactLastWeekItem = 'assets/profile/profile_contact_blue_image.png';
  static const String iconEditPrices = 'assets/profile/icon_edit_prices.png';
  static const String imagePersonalGreetEmpty = 'assets/profile/profile_greet_empty.png';
  static const String iconPersonalGreetPin = 'assets/profile/profile_greet_pin_icon.png';
  static const String iconPersonalGreetUse = 'assets/profile/profile_greet_status_icon_2.png';
  static const String iconPersonalGreetReview = 'assets/profile/profile_greet_status_icon_1.png';
  static const String iconPersonalGreetReviewFail = 'assets/profile/profile_greet_status_icon_1.png';
  static const String iconPersonalGreetEdit = 'assets/profile/profile_greet_edit_icon.png';
  static const String imagePersonalGreetVoice = 'assets/profile/profile_greet_voice_icon.png';
  static const String iconRealtimeDepositActivate = 'assets/icons/icon_realtime_deposit_activate.png';
  static const String iconRealtimeDepositDeactivate = 'assets/icons/icon_realtime_deposit_deactivate.png';
  static const String iconBenefitCloudCheckActivate = 'assets/icons/icon_check_activate.png';
  static const String iconBenefitCloudCheckDeactivate = 'assets/icons/icon_check_deactivate.png';
  static const String imgEmptyBookkeepingBanner = 'assets/images/img_empty_bookkeeping_banner.png';
  static const String iconClose = 'assets/images/icon_close.png';
  static const String iconCalendar = 'assets/images/icon_calendar.png';
  static const String iconChatMessageSending = 'assets/images/icon_message_sending.png';
  static const String iconChatMessageResend = 'assets/images/icon_message_resend.png';
  static const String iconChatMessageError = 'assets/images/icon_message_error.png';
  static const String iconChatMessageReviewWarning = 'assets/icons/icon_chat_message_review_warning.png';
  static const String imgStrikeUpListBg = 'assets/strike_up_list/frechat/img_strike_up_list_bg.png';
  static const String imgInviteFriendBanner = 'assets/images/invite_friend_banner.png';
  static const String firstRechargeBanner = 'assets/images/first_recharge_banner.png';
  static const String iconProfileRealPersonAuthError = 'assets/profile/icon_profile_real_person_auth_error.png';



  // Chat Message
  static const String iconRecordPlaySelf = 'assets/images/icon_record_play_self.png';
  static const String iconRecordPlayOpposite = 'assets/images/icon_record_play_opposite.png';
  static const String iconWaveform = 'assets/images/icon_waveform.png';


  static const String iconCallOpposite = 'assets/icons/chat_message/icon_call_opposite.png';
  static const String iconCallPersonal = 'assets/icons/chat_message/icon_call_personal.png';
  static const String iconVideoOpposite = 'assets/icons/chat_message/icon_video_opposite.png';
  static const String iconVideoPersonal = 'assets/icons/chat_message/icon_video_personal.png';
  static const String iconCallCancelOpposite = 'assets/icons/chat_message/icon_cancel_call_opposite.png';
  static const String iconCallCancelPersonal = 'assets/icons/chat_message/icon_cancel_call_personal.png';
  static const String iconVideoCancelOpposite = 'assets/icons/chat_message/icon_cancel_video_opposite.png';
  static const String iconVideoCancelPersonal = 'assets/icons/chat_message/icon_cancel_video_personal.png';




}

